import math
a = int(input("Enter an angle in degrees:"))
sine = math.asin(a)
cosecant = math.asinh(a)
cosine = math.acos(a)
print("sin:", sine)
print("csc:", cosecant)
print("cos:", cosine)
secant = math.acosh(a)
tangent = math.atan(a)
cotangent = math.atanh(a)
print("sec:", secant)
print("tan:", tangent)
print("cot:", cotangent)